// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        ElAvatar: (typeof import('element-plus/es'))['ElAvatar'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
        Navbar: (typeof import('./src/components/business/Navbar/index.vue'))['default'];
        PageLoading: (typeof import('./src/components/business/PageLoading/index.vue'))['default'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
        SliderMenu: (typeof import('./src/components/business/SliderMenu/index.vue'))['default'];
    }
}
